const DISPATCH_STATUSES = {
  NEW: 'NEW',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  MAIN_DISPATCHED: 'MAIN_DISPATCHED',
  EXCESS_DISPATCHED: 'EXCESS_DISPATCHED',
  LOCAL_DISPATCHED: 'LOCAL_DISPATCHED',
  DRIVER_SELECTED: 'DRIVER_SELECTED',
  DETAILS_SENT: 'DETAILS_SENT',
  ETA_CONFIRMED: 'ETA_CONFIRMED',
  COVERED: 'COVERED',
  PICKED_UP: 'PICKED_UP',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NEEDS_REVIEW: 'NEEDS_REVIEW',
};

const DISPATCH_ACTORS = {
  OWNER: 'OWNER',
  AI: 'AI',
  SYSTEM: 'SYSTEM',
};

const VEHICLE_REQUIREMENTS = {
  ANY_SUITABLE: 'ANY_SUITABLE',
  SUV_OR_MAXI: 'SUV_OR_MAXI',
  MAXI: 'MAXI',
  SUV: 'SUV',
  WHEELCHAIR: 'WHEELCHAIR',
  CHILD_SEAT: 'CHILD_SEAT',
};

const PASSENGER_ASSUMPTIONS = {
  UP_TO_4: 'UP_TO_4',
};

module.exports = {
  DISPATCH_ACTORS,
  DISPATCH_STATUSES,
  PASSENGER_ASSUMPTIONS,
  VEHICLE_REQUIREMENTS,
};
